"use client";

import { useGLTF } from "@react-three/drei";

interface HeadstoneMeshProps {
  /** Path to the GLB model file */
  modelPath: string;
  /** Scale factor */
  scale: number;
}

/**
 * Renders a tombstone headstone from a GLB model (generated by Meshy AI).
 * The model includes the full headstone with textures.
 */
export function HeadstoneMesh({ modelPath, scale }: HeadstoneMeshProps) {
  const { scene } = useGLTF(modelPath);

  return (
    <primitive
      object={scene.clone()}
      scale={[scale, scale, scale]}
      castShadow
      receiveShadow
    />
  );
}
